/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/rafal-bigaj/code-engine-batch-job-client/pkg/apis/codeengine/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJobRuns implements JobRunInterface
type FakeJobRuns struct {
	Fake *FakeCodeengineV1beta1
	ns   string
}

var jobrunsResource = schema.GroupVersionResource{Group: "codeengine.cloud.ibm.com", Version: "v1beta1", Resource: "jobruns"}

var jobrunsKind = schema.GroupVersionKind{Group: "codeengine.cloud.ibm.com", Version: "v1beta1", Kind: "JobRun"}

// Get takes name of the jobRun, and returns the corresponding jobRun object, and an error if there is any.
func (c *FakeJobRuns) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.JobRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jobrunsResource, c.ns, name), &v1beta1.JobRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.JobRun), err
}

// List takes label and field selectors, and returns the list of JobRuns that match those selectors.
func (c *FakeJobRuns) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.JobRunList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jobrunsResource, jobrunsKind, c.ns, opts), &v1beta1.JobRunList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.JobRunList{ListMeta: obj.(*v1beta1.JobRunList).ListMeta}
	for _, item := range obj.(*v1beta1.JobRunList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jobRuns.
func (c *FakeJobRuns) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jobrunsResource, c.ns, opts))

}

// Create takes the representation of a jobRun and creates it.  Returns the server's representation of the jobRun, and an error, if there is any.
func (c *FakeJobRuns) Create(ctx context.Context, jobRun *v1beta1.JobRun, opts v1.CreateOptions) (result *v1beta1.JobRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jobrunsResource, c.ns, jobRun), &v1beta1.JobRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.JobRun), err
}

// Update takes the representation of a jobRun and updates it. Returns the server's representation of the jobRun, and an error, if there is any.
func (c *FakeJobRuns) Update(ctx context.Context, jobRun *v1beta1.JobRun, opts v1.UpdateOptions) (result *v1beta1.JobRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jobrunsResource, c.ns, jobRun), &v1beta1.JobRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.JobRun), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJobRuns) UpdateStatus(ctx context.Context, jobRun *v1beta1.JobRun, opts v1.UpdateOptions) (*v1beta1.JobRun, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(jobrunsResource, "status", c.ns, jobRun), &v1beta1.JobRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.JobRun), err
}

// Delete takes name of the jobRun and deletes it. Returns an error if one occurs.
func (c *FakeJobRuns) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(jobrunsResource, c.ns, name, opts), &v1beta1.JobRun{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJobRuns) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jobrunsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.JobRunList{})
	return err
}

// Patch applies the patch and returns the patched jobRun.
func (c *FakeJobRuns) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.JobRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jobrunsResource, c.ns, name, pt, data, subresources...), &v1beta1.JobRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.JobRun), err
}
