/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/rafalbigaj/code-engine-batch-job-client/pkg/apis/codeengine/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJobDefinitions implements JobDefinitionInterface
type FakeJobDefinitions struct {
	Fake *FakeCodeengineV1beta1
	ns   string
}

var jobdefinitionsResource = schema.GroupVersionResource{Group: "codeengine.cloud.ibm.com", Version: "v1beta1", Resource: "jobdefinitions"}

var jobdefinitionsKind = schema.GroupVersionKind{Group: "codeengine.cloud.ibm.com", Version: "v1beta1", Kind: "JobDefinition"}

// Get takes name of the jobDefinition, and returns the corresponding jobDefinition object, and an error if there is any.
func (c *FakeJobDefinitions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.JobDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jobdefinitionsResource, c.ns, name), &v1beta1.JobDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.JobDefinition), err
}

// List takes label and field selectors, and returns the list of JobDefinitions that match those selectors.
func (c *FakeJobDefinitions) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.JobDefinitionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jobdefinitionsResource, jobdefinitionsKind, c.ns, opts), &v1beta1.JobDefinitionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.JobDefinitionList{ListMeta: obj.(*v1beta1.JobDefinitionList).ListMeta}
	for _, item := range obj.(*v1beta1.JobDefinitionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jobDefinitions.
func (c *FakeJobDefinitions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jobdefinitionsResource, c.ns, opts))

}

// Create takes the representation of a jobDefinition and creates it.  Returns the server's representation of the jobDefinition, and an error, if there is any.
func (c *FakeJobDefinitions) Create(ctx context.Context, jobDefinition *v1beta1.JobDefinition, opts v1.CreateOptions) (result *v1beta1.JobDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jobdefinitionsResource, c.ns, jobDefinition), &v1beta1.JobDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.JobDefinition), err
}

// Update takes the representation of a jobDefinition and updates it. Returns the server's representation of the jobDefinition, and an error, if there is any.
func (c *FakeJobDefinitions) Update(ctx context.Context, jobDefinition *v1beta1.JobDefinition, opts v1.UpdateOptions) (result *v1beta1.JobDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jobdefinitionsResource, c.ns, jobDefinition), &v1beta1.JobDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.JobDefinition), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJobDefinitions) UpdateStatus(ctx context.Context, jobDefinition *v1beta1.JobDefinition, opts v1.UpdateOptions) (*v1beta1.JobDefinition, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(jobdefinitionsResource, "status", c.ns, jobDefinition), &v1beta1.JobDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.JobDefinition), err
}

// Delete takes name of the jobDefinition and deletes it. Returns an error if one occurs.
func (c *FakeJobDefinitions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(jobdefinitionsResource, c.ns, name, opts), &v1beta1.JobDefinition{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJobDefinitions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jobdefinitionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.JobDefinitionList{})
	return err
}

// Patch applies the patch and returns the patched jobDefinition.
func (c *FakeJobDefinitions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.JobDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jobdefinitionsResource, c.ns, name, pt, data, subresources...), &v1beta1.JobDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.JobDefinition), err
}
