/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/rafalbigaj/code-engine-batch-job-client/pkg/apis/codeengine/v1beta1"
	scheme "github.com/rafalbigaj/code-engine-batch-job-client/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JobRunsGetter has a method to return a JobRunInterface.
// A group's client should implement this interface.
type JobRunsGetter interface {
	JobRuns(namespace string) JobRunInterface
}

// JobRunInterface has methods to work with JobRun resources.
type JobRunInterface interface {
	Create(ctx context.Context, jobRun *v1beta1.JobRun, opts v1.CreateOptions) (*v1beta1.JobRun, error)
	Update(ctx context.Context, jobRun *v1beta1.JobRun, opts v1.UpdateOptions) (*v1beta1.JobRun, error)
	UpdateStatus(ctx context.Context, jobRun *v1beta1.JobRun, opts v1.UpdateOptions) (*v1beta1.JobRun, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.JobRun, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.JobRunList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.JobRun, err error)
	JobRunExpansion
}

// jobRuns implements JobRunInterface
type jobRuns struct {
	client rest.Interface
	ns     string
}

// newJobRuns returns a JobRuns
func newJobRuns(c *CodeengineV1beta1Client, namespace string) *jobRuns {
	return &jobRuns{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the jobRun, and returns the corresponding jobRun object, and an error if there is any.
func (c *jobRuns) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.JobRun, err error) {
	result = &v1beta1.JobRun{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jobruns").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of JobRuns that match those selectors.
func (c *jobRuns) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.JobRunList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.JobRunList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jobruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested jobRuns.
func (c *jobRuns) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("jobruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a jobRun and creates it.  Returns the server's representation of the jobRun, and an error, if there is any.
func (c *jobRuns) Create(ctx context.Context, jobRun *v1beta1.JobRun, opts v1.CreateOptions) (result *v1beta1.JobRun, err error) {
	result = &v1beta1.JobRun{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("jobruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jobRun).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a jobRun and updates it. Returns the server's representation of the jobRun, and an error, if there is any.
func (c *jobRuns) Update(ctx context.Context, jobRun *v1beta1.JobRun, opts v1.UpdateOptions) (result *v1beta1.JobRun, err error) {
	result = &v1beta1.JobRun{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jobruns").
		Name(jobRun.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jobRun).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *jobRuns) UpdateStatus(ctx context.Context, jobRun *v1beta1.JobRun, opts v1.UpdateOptions) (result *v1beta1.JobRun, err error) {
	result = &v1beta1.JobRun{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jobruns").
		Name(jobRun.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jobRun).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the jobRun and deletes it. Returns an error if one occurs.
func (c *jobRuns) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jobruns").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *jobRuns) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jobruns").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched jobRun.
func (c *jobRuns) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.JobRun, err error) {
	result = &v1beta1.JobRun{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("jobruns").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
